@startuml
'https://plantuml.com/class-diagram

abstract class Animal{
+ greeting():void (abstract)
}
class Cat extends Animal{
+ greeting():void <- "Meow"
}
class Dog extends Animal{
+ greeting():void <- "Wooof"
+ greeting(another:Dog):void <- "Wooooof"
}
class BigDog extends Dog{
+ greeting():void <- "Wooow"
+ greeting(another:Dog):void<- "Wooooow"
+ greeting(another:BigDog):void<- "Woooooooooooooow"
}


@enduml